web:
  context: /kitchen-sink

environment:
  RACK_ENV: production

queues:
  /queues/a-kitchen-sink-queue:

topics:
  /topics/a-kitchen-sink-topic:

messaging:
  /queues/a-kitchen-sink-queue:
    QueueProcessor
  /topics/a-kitchen-sink-topic:
    - OneTopicProcessor
    - AnotherTopicProcessor
    
services:
  AService:
  StatsService:
    config:
      sample_period: 10_000
      output_directory: tmp
      queues:
        - '/queues/a-kitchen-sink-queue'

jobs:
  message.producer:
    job: MessageProducer
    cron: "* * * * * ?"

ruby:
  interactive: true    
